### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by gcbishal** [thenifemi/flutter_polls#10]
I just used the example code and ran into error.

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.1)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

```
The following _TypeError was thrown building FlutterPolls(dirty, useState<bool>: false, useState<bool>: true, useState<PollOption?>: Instance of 'PollOption', useState<int>: 572):
type '(dynamic, dynamic) => dynamic' is not a subtype of type '(PollOption, PollOption) => PollOption' of 'combine'

The relevant error-causing widget was
FlutterPolls
lib\…\post_dependent_widgets\poll_card.dart:86
When the exception was thrown, this was the stack
#0      ListMixin.reduce (dart:collection/list.dart)
#1      FlutterPolls.build.<anonymous closure> (package:flutter_polls/flutter_polls.dart:243:42)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#4      List.addAll (dart:core-patch/growable_array.dart:319:13)
#5      FlutterPolls.build (package:flutter_polls/flutter_polls.dart:218:26)
#6      StatelessElement.build
package:flutter/…/widgets/framework.dart:4876
#7      HookElement.build (package:flutter_hooks/src/framework.dart:416:27)
#8      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4806
#9      Element.rebuild
package:flutter/…/widgets/framework.dart:4529
#10     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2659
#11     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:891
#12     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:370
#13     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
#14     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1083
#15     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:997
#19     _invoke (dart:ui/hooks.dart:151:10)
#20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#21     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```

**Comment by gcbishal** [comment]
### Package update required
Fixed ✔️

``` final List<dynamic> pollOptions; ```
to
``` final List<PollOption> pollOptions;```

or cast dynamic to PollOption instance while reducing the options

**Comment by thenifemi** [comment]
Hi, sorry, I don't understand the issue. Could you explain better?

**Comment by jalchr** [comment]
I'm facing the same issue. 
Once I tap on_Voted is triggered causing this error

**Comment by thenifemi** [comment]
`onVoted` should be implemented this way: `onVoted: (PollOption pollOption, int newTotalVotes) { }`

**Comment by gcbishal** [comment]
> `onVoted` should be implemented this way: `onVoted: (PollOption pollOption, int newTotalVotes) { }`

Yeah better just swap the dynamic to PollOption.

**Comment by gcbishal** [comment]
> `onVoted` should be implemented this way: `onVoted: (PollOption pollOption, int newTotalVotes) { }`

And the voted poll changes without the new value. It also needs to be fixed.

**Comment by gcbishal** [comment]
> > > `onVoted` should be implemented this way: `onVoted: (PollOption pollOption, int newTotalVotes) { }`
> > 
> > Yeah better just swap the dynamic to PollOption.
> 
> Yeah, I have tried that but since devs would pass `dynamic` lists and not `PollOption`, it would also throw a type error

I just changed the pollOption instance field with PollOption type rather than dynamic. And it's working fine. Not having any issue

**Comment by thenifemi** [comment]
> > `onVoted` should be implemented this way: `onVoted: (PollOption pollOption, int newTotalVotes) { }`
> 
> And the voted poll changes without the new value. It also needs to be fixed.

Could you elaborate on this?

**Comment by thenifemi** [comment]
> 



> > > > `onVoted` should be implemented this way: `onVoted: (PollOption pollOption, int newTotalVotes) { }`
> > > 
> > > 
> > > Yeah better just swap the dynamic to PollOption.
> > 
> > 
> > Yeah, I have tried that but since devs would pass `dynamic` lists and not `PollOption`, it would also throw a type error
> 
> I just changed the pollOption instance field with PollOption type rather than dynamic. And it's working fine. Not having any issue

And how are you passing your PollOption data?

**Comment by thenifemi** [comment]
@gcbishal Thanks for your contribution 🚀
