### ISSUE TITLE
RRect argument contained a NaN value

### ISSUE THREAD

**Issue by amuslimreno** [thenifemi/flutter_polls#15]
Create Problem:

1. Pass List of PollOption via pollOptions prameter with corresponding field votes set to 0
2. set pollEnded parameter to true

Solution: resolve 0/0 = 0, not NaN

line 252. percent: pollOption.votes / totalVotes.value

**Comment by thenifemi** [comment]
@amuslimreno Hey! I can't seem to reproduce the error

<img width="1004" alt="Screenshot 2022-10-30 at 13 13 56" src="https://user-images.githubusercontent.com/38212839/198889321-8f73f0f6-8846-43d8-81da-2e9de89cc319.png">

<img width="484" alt="Screenshot 2022-10-30 at 13 14 42" src="https://user-images.githubusercontent.com/38212839/198889361-51b4a38c-1ee8-4e3e-9aff-5528403429e5.png">

**Comment by amuslimreno** [comment]
Hi there,
I get the error if I run your example project. "Another exception was thrown: RRect argument contained a NaN value."
![image](https://user-images.githubusercontent.com/115142866/198971315-04783917-68e8-4623-bcd2-3e1cb0b21513.png)

The reason is quite clear. If nobody votes, "totalVotes"(line 220) will be 0. And if you divide by zero, you get the error. 
You actually fixed it in line 286, but forgot to add the same statement to line 252.

**Comment by thenifemi** [comment]
Got it!
Pushed and publish a fix https://github.com/thenifemi/flutter_polls/commit/d29254fa54b18185e8c34f34c2f3faee280f3525

Please let me know if you are still facing this issue.

**Comment by amuslimreno** [comment]
Perfect, thanks. Keep the good work up!
