### ISSUE TITLE
hasVoted showing `Bad state: No element` when value set to true

### ISSUE THREAD

**Issue by jerrypaulsam** [thenifemi/flutter_polls#17]
hasVoted showing `Bad state: No element` when value set to true

`======== Exception caught by widgets library =======================================================
The following StateError was thrown building FlutterPolls(dirty, useState<bool>: false, useState<bool>: false, useState<bool>: false):
Bad state: No element`

**Comment by destbest94** [comment]
Hi, how you fix it?

**Comment by thenifemi** [comment]
@destbest94 Are you still facing this issue?

**Comment by Ameenhamed** [comment]
hello 
The following StateError was thrown building FlutterPolls(dirty, useState<bool>: true, useState<bool>: false, useState<bool>: false):

**Comment by Ameenhamed** [comment]
I'm having the same problem

**Comment by Ameenhamed** [comment]
hello
The following StateError was thrown building FlutterPolls(dirty, useState: true, useState: false, useState: false):


I'm having the same problem


![image](https://github.com/thenifemi/flutter_polls/assets/54305859/7608db01-6f71-4ab1-a535-06c27f324ea1)

**Comment by jyo142** [comment]
I had this issue too in version 0.1.5 when setting hasVoted = true and was able to fix it by populating the `userVotedId` field to be the id of the option that the voter has voted

```
  /// If a user has already voted in this poll.
  /// It is ignored if [hasVoted] is set to false or not set at all.
  final String? userVotedOptionId;
```
