### ISSUE TITLE
Make the PollOption id type to String.

### ISSUE THREAD

**Issue by samuelrbrt** [thenifemi/flutter_polls#26]
```
    PollOption(
        id: choice.key, <--- Int
        title: AutoSizeText(
          choice.title,
          style: primary14TextStyle,
        ),
        votes: choice.votes,
    );
```

Currently the PollOption id is an integer, now a days it's very common to use UUID string instead of int to index items in the server side for various reasons. So at the Flutter app side, we usually end up using the same option id returned by the API to uniquely identify the Poll options.

Would it be possible to change the `id` type to String to accomodate more such use cases?

**Comment by thenifemi** [comment]
Great insight! [Fixed](https://github.com/thenifemi/flutter_polls/commit/10653fbb87bef557b7cdc4728f505c0a0e31f7d6).

**Comment by samuelrbrt** [comment]
@thenifemi Thanks for the fix. Just one more thing, the corresponding `userVotedOptionId` in the `FlutterPolls` class should also be updated accordingly.
