### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by biancashouse** [thenifemi/flutter_polls#29]
Would be really nice if you could update the pkg deps.
E.g. flutter hooks is now at version 0.20.3.
Many thanks for the work anyway. Very nice.

**Comment by thenifemi** [comment]
Hey @biancashouse 

Fixed on [v0.1.6](https://github.com/thenifemi/flutter_polls/releases/tag/v0.1.6)

Thanks for your patience.
Nifemi.
